### ISSUE TITLE
GDB Register Print Support in `RISCVVGDBCore.h`

### ISSUE THREAD

**Issue by fabianpedd** [tum-ei-eda/M2-ISA-R#8]
As of now, M2-ISA-R does not generate any code for register printing via GDB in `RISCVVGDBCore.h`. It only provides a comment  `Further register should be added here to send data over gdbserver`. Is that intended? 

The ArchImpl in ETISS has the [mapRegister](https://github.com/tum-ei-eda/etiss/blob/master/ArchImpl/RISCV/RISCVGDBCore.h#L73) method already implemented.

**Comment by wysiwyng** [comment]
This behavior is indeed intended at the moment. Several features have to be added manually to the generated models: exception behavior, MMU, decoding of variable-length instructions, endianness conversion, GDB server stuff and others. This tool's predecessor also did not generate these parts, simply because it had no way to do so. The situation has not changed very much unfortunately, although generating exception behavior is a planned feature for the future.

For your specific case, you can most likely just copy over the non-generated parts from the existing files in ETISS.
